name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    name: Build y tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet build RedSismica.sln -c Release
      - run: dotnet test RedSismica.sln -c Release --no-build --logger "console;verbosity=normal"
